version: "3"

services:
  elasticsearch-test:
    container_name: elasticsearch-test
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    environment:
      - node.name=es
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es
      - cluster.name=docker-local
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
      - bootstrap.system_call_filter=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - es-data:/usr/share/elasticsearch/data
  kibana-test:
    container_name: kibana-test
    build:
      context: ./kibana
      dockerfile: Dockerfile
    ports:
      - 5601:5601
volumes:
  es-data: